ecommerce/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, add_to_cart, show_cart, remove_from_cart, CheckoutView
from . import views


app_name = 'ecommerce'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('cart/', views.show_cart, name='show-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from ecommerce import urls as ecommerce_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

app_name = 'ecommerce'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(ecommerce_urls, namespace="ecommerce")),
    re_path('accounts/', include('allauth.urls')), # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models
from django.conf import settings
from sorl.thumbnail import ImageField
from django.shortcuts import reverse, redirect

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    image = ImageField(upload_to='commerce', blank=True)
    description = models.TextField(max_length=250, default="item description in here")
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_urls(self):
        return reverse("ecommerce:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("ecommerce:add_to_cart", kwargs={
            'slug':self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("ecommerce:remove_from_cart", kwargs={
            'slug':self.slug
        })
    
    def get_checkout_url(self):
        return reverse("ecommerce:checkout", kwargs={
        'slug':self.slug
    })



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_total_price_url(self):
        return self.quantity * Item.price

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)



    def __str__(self):
        return self.user.username

ecommerce/forms.py
from django import forms
from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : '1234 Malibongwe dr'
    }))
    apartment_address = forms.CharField()
    country = CountryField(blank_label='(select country)')
    zp = forms.CharField()
    same_billing_address = forms.BooleanField(widget=forms.CheckboxInput())
    save_info = forms.BooleanField(widget=forms.CheckboxInput())
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES
    )

ecommerce/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .models import Item, OrderItem, Order
from django.contrib.auth.decorators import login_required
from .forms import CheckoutForm

# Create your views here.

class HomeView(ListView):
    model = Item
    template_name = "home.html"

# def item_list(request):
#     context = {
#         'items': Item.objects.all()
#     }
#     return render(request, 'item-list.html', context)

def products(request):
    context = {
        'items': Item.objects.all()
    }
    return render(request, 'product.html', context)

class ItemDetailView(DetailView):
    http_method_names = ['get']
    model = Item
    template_name = "product.html"
    context_object_name = "product"

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        ordered=False,
        user=request.user
        )
    order_qs = Order.objects.filter(user=request.user, ordered= False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
        else:
            order.items.add(order_item)
    else:
        order_date = timezone.now()
        order = Order.objects.create(user=request.user,
                                     order_date=order_date)
        order.items.add(order_item)
    return redirect("ecommerce:product", slug=slug)

def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
        item=item,
        ordered=False,
        user=request.user
        )[0]
            order.items.remove(order_item)
        else:
            return redirect("ecommerce:product", slug=slug)
    else:
        return redirect("ecommerce:product", slug=slug)
    return redirect("ecommerce:product", slug=slug)


@login_required
def show_cart(request, *args, **kwargs):
    user = request.user
    try:
        cart = Order.objects.get( ordered=False)
        # cart = Order.objects.filter(user=user)
        context = {
            'object': cart
        }
        amount = 0
        # for item in cart:
        #     value = item.quantity * item.price
        #     amount = amount + value
        #     total_price = amount + 90
        return render(request, 'cart.html', context)
    except ObjectDoesNotExist:
        messages.error(request, "You do not have an active order")
        return redirect("/")

class CheckoutView(DetailView):
    def get(self, *args, **kwargs):
        form = CheckoutForm
        context = {
            'form': form
        }
        return render(self.request, "checkout.html", context)
    
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        if form.is_valid():
            print("the form is valid")
            return redirect('ecommerce:checkout')

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Document{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

ecommerce/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">
        <!-- Toggle button -->
        <button 
            class="navbar-toggler" 
            type="button" 
            data-mdb-toggle="collapse" 
            data-mdb-target="#navbarSupportedContent1" 
            aria-controls="navbarSupportedContent1" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-sm-0" href="{% url 'ecommerce:home' %}">
                <img src="{% static 'ecommerce/images/store-icon.svg' %}" height="20" alt="MDB Logo" loading="lazy" />
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="https://mdbootstrap.com/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://mdbootstrap.com/docs/standard/">About MDB</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://mdbootstrap.com/docs/standard/getting-started/installation/">Free download</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://mdbootstrap.com/education/bootstrap/">Free tutorials</a>
                </li>
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <!-- Icon -->
            <a class="nav-link me-3" href="{% url 'ecommerce:show-cart' %}">
                <img src="{% static 'ecommerce/images/cart4.svg' %}" alt="cart">
                <span class="badge rounded-pill badge-notification bg-danger">0</span>
            </a>

            <a href="https://github.com/mbuso-08/django-store-project" class="border rounded px-2 nav-link" target="_blank"> <i class="fab fa-github me-2"></i>GitHub </a>
        </div>
        <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
</nav>
<!-- Navbar -->



<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Cart - 2 items</h5>
          </div>
          <div class="card-body">
          {% for order_item in object.items.all %}
            <!-- Single item -->
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="{{ order_item.item.image.url }}"
                    class="w-100" alt="Blue Jeans Jacket" />
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong>{{ order_item.item.title }}</strong></p>
                <p>Color: blue</p>
                <p>Size: M</p>
                <a href="{{ object.get_remove_from_cart_url }}"><button class="btn btn-success ms-1" >
                    <img src="{% static 'ecommerce/images/trash3.svg' %}" alt="cart" />
                    <i class="fas fa-shopping-cart ms-1"></i>
                </button></a>
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                <!-- Quantity -->
                <div class="d-flex mb-4" style="max-width: 300px">
                  <button class="btn btn-primary px-3 me-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>

                  <div class="form-outline">
                    <input id="form1" min="0" name="quantity" value="{{ order_item.quantity }}" type="number" class="form-control" />
                    <label class="form-label" for="form1">Quantity</label>
                  </div>

                  <button class="btn btn-primary px-3 ms-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong>{{ order_item.item.price }}</strong>
                </p>
                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />

            <!-- Single item -->

            <!-- Single item -->
          {% endfor %}
          </div>
          
        </div>
        <div class="card mb-4">
          <div class="card-body">
            <p><strong>Expected shipping delivery</strong></p>
            <p class="mb-0">12.10.2020 - 14.10.2020</p>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>We accept</strong></p>
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
              alt="Visa" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
              alt="American Express" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
              alt="Mastercard" />
            <img class="me-2" width="45px"
              src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
              alt="PayPal acceptance mark" />
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                Products
                <span>{{ get_total_price_url }}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Shipping
                <span>Gratis</span>
              </li>
              <li
                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                
                <div>
                  <strong>Total amount</strong>
                  <strong>
                    <p class="mb-0">(including VAT)</p>
                  </strong>
                </div>
                {% comment %} {% for item in object.items.all %} {% endcomment %}
                <span><strong>R{{ get_total_price_url }}</strong></span>
                {% comment %} {% endfor %} {% endcomment %}
              </li>
            </ul>

            <a href="/checkout/"><button type="button" class="btn btn-primary btn-lg btn-block">
              Go to checkout
            </button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

ecommerce/templates/home.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} Motor Mods Store {% endblock %}
{% block content %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="16"
  height="16"
  fill="currentColor"
  class="bi bi-cart4"
  viewBox="0 0 16 16"
>
  <path
    d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"
  />
</svg>
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent1"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent1">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-sm-0" href="{% url 'ecommerce:home' %}">
        <img
          src="{% static 'ecommerce/images/store-icon.svg' %}"
          height="20"
          alt="Store Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="https://mdbootstrap.com/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://mdbootstrap.com/docs/standard/"
            >About MDB</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="https://mdbootstrap.com/docs/standard/getting-started/installation/"
            >Free download</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="https://mdbootstrap.com/education/bootstrap/"
            >Free tutorials</a
          >
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <a class="nav-link me-3" href="{% url 'ecommerce:show-cart' %}">
        <img src="{% static 'ecommerce/images/cart4.svg' %}" alt="cart" />
        <span class="badge rounded-pill badge-notification bg-danger">0</span>
      </a>
      <a
        href="https://github.com/mbuso-08/django-store-project"
        class="border rounded px-2 nav-link"
        target="_blank"
      >
        <i class="fab fa-github me-2"></i>GitHub
      </a>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<div
  id="carouselExampleAutoplaying"
  class="carousel slide h-25"
  data-bs-ride="carousel"
>
  <div
    class="carousel-inner"
    style="width: 100%; height: 500px; object-fit: cover"
  >
    <div class="carousel-item active h-25">
      <img
        src="{% static 'ecommerce/images/bmwf82m410.jpg' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'ecommerce/images/Carbon-Fiber-Interior.jpg' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'ecommerce/images/front-lip.jpg' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleAutoplaying"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleAutoplaying"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container text-center">
  <div class="row">
  {% for item in object_list %}
    <div class="col">
      <div class="card my-4" style="width: 18rem">
        <a href="{{ item.get_absolute_urls }}"><img
          src="{{ item.image.url }}"
          class="card-img-top"
          alt="..."
          style="height: 300px"
        /></a>
        <div class="card-body">
          <h5 class="card-title">Steering Wheel</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="#" class="btn btn-success">R{{ item.price }}</a>
        </div>
      </div>
    </div>
   
  {% endfor %}
  </div>
</div>

<nav
  aria-label="Page navigation example"
  class="d-flex justify-content-center mt-3"
>
  <ul class="pagination">
    <li class="page-item disabled">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li class="page-item active"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">4</a></li>
    <li class="page-item"><a class="page-link" href="#">5</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

<hr class="text-dark" />

<div class="container">
  <!-- Section: Social media -->
  <section class="mb-3">
    <!-- Facebook -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-facebook-f"></i
    ></a>

    <!-- Twitter -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-twitter"></i
    ></a>

    <!-- Google -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-google"></i
    ></a>

    <!-- Instagram -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-instagram"></i
    ></a>

    <!-- YouTube -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-youtube"></i
    ></a>
    <!-- Github -->
    <a
      class="btn-link btn-floating btn-lg text-white"
      href="#!"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="fab fa-github"></i
    ></a>
  </section>
  <!-- Section: Social media -->
</div>
<!-- Grid container -->
{% endblock %}